version: "3.9"

services:
  interacao-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interacao-api-container
    restart: always
    ports:
      - "3000:3009"
    environment:
      NODE_ENV: production
      PORT: 3000
